name: Build and Test

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup java JDK
      uses: actions/setup-java@v4.5.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3.5.0

    - name: Fix Gradle Wrapper Permissions
      run: chmod +x gradlew
      
    - name: Build project
      run: ./gradlew build
